#include <stdio.h>

void print_mem_macros() {
    printf("// ============================================================================\n");
    printf("// Memory Management Declarations\n");
    printf("// ============================================================================\n\n");
    printf("#define SLA_DECLARE_MEM_FUNCTIONS(TYPE, PREFIX) \\\n");
    printf("    PREFIX##_dense_vec PREFIX##_dense_vec_alloc(size_t size); \\\n");
    printf("    void PREFIX##_dense_vec_free(PREFIX##_dense_vec *v); \\\n");
    printf("    PREFIX##_coo_vec PREFIX##_coo_vec_alloc(size_t size, size_t nnz); \\\n");
    printf("    void PREFIX##_coo_vec_free(PREFIX##_coo_vec *v); \\\n");
    printf("    PREFIX##_dense_mat PREFIX##_dense_mat_alloc(size_t rows, size_t cols); \\\n");
    printf("    void PREFIX##_dense_mat_free(PREFIX##_dense_mat *m); \\\n");
    printf("    PREFIX##_csr_mat PREFIX##_csr_mat_alloc(size_t rows, size_t cols, size_t nnz); \\\n");
    printf("    void PREFIX##_csr_mat_free(PREFIX##_csr_mat *m); \\\n");
    printf("    PREFIX##_dia_mat PREFIX##_dia_mat_alloc(size_t rows, size_t cols, size_t num_diags); \\\n");
    printf("    void PREFIX##_dia_mat_free(PREFIX##_dia_mat *m); \\\n");
    printf("    void PREFIX##_dense_vec_map_to_device(PREFIX##_dense_vec *v); \\\n");
    printf("    void PREFIX##_dense_vec_update_from_device(PREFIX##_dense_vec *v); \\\n");
    printf("    void PREFIX##_dense_vec_unmap_from_device(PREFIX##_dense_vec *v); \\\n");
    printf("    void PREFIX##_coo_vec_map_to_device(PREFIX##_coo_vec *v); \\\n");
    printf("    void PREFIX##_coo_vec_update_from_device(PREFIX##_coo_vec *v); \\\n");
    printf("    void PREFIX##_coo_vec_unmap_from_device(PREFIX##_coo_vec *v); \\\n");
    printf("    void PREFIX##_dense_mat_map_to_device(PREFIX##_dense_mat *m); \\\n");
    printf("    void PREFIX##_dense_mat_update_from_device(PREFIX##_dense_mat *m); \\\n");
    printf("    void PREFIX##_dense_mat_unmap_from_device(PREFIX##_dense_mat *m); \\\n");
    printf("    void PREFIX##_csr_mat_map_to_device(PREFIX##_csr_mat *m); \\\n");
    printf("    void PREFIX##_csr_mat_update_from_device(PREFIX##_csr_mat *m); \\\n");
    printf("    void PREFIX##_csr_mat_unmap_from_device(PREFIX##_csr_mat *m); \\\n");
    printf("    void PREFIX##_dia_mat_map_to_device(PREFIX##_dia_mat *m); \\\n");
    printf("    void PREFIX##_dia_mat_update_from_device(PREFIX##_dia_mat *m); \\\n");
    printf("    void PREFIX##_dia_mat_unmap_from_device(PREFIX##_dia_mat *m);\n\n");
    printf("SLA_DECLARE_MEM_FUNCTIONS(sla_f32, sla_f32)\n");
    printf("SLA_DECLARE_MEM_FUNCTIONS(sla_f64, sla_f64)\n");
    printf("SLA_DECLARE_MEM_FUNCTIONS(sla_c32, sla_c32)\n");
    printf("SLA_DECLARE_MEM_FUNCTIONS(sla_c64, sla_c64)\n\n");

    printf("// ============================================================================\n");
    printf("// Memory Management Implementations\n");
    printf("// ============================================================================\n\n");

    printf("#define SLA_IMPLEMENT_MEM_FUNCTIONS(TYPE, PREFIX) \\\n");
    printf("    PREFIX##_dense_vec PREFIX##_dense_vec_alloc(size_t size) { \\\n");
    printf("        PREFIX##_dense_vec v; \\\n");
    printf("        v.size = size; \\\n");
    printf("        v.data = (TYPE*)calloc(size, sizeof(TYPE)); \\\n");
    printf("        return v; \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_vec_free(PREFIX##_dense_vec *v) { \\\n");
    printf("        if (v->data) free(v->data); \\\n");
    printf("        v->data = NULL; \\\n");
    printf("        v->size = 0; \\\n");
    printf("    } \\\n");
    printf("    PREFIX##_coo_vec PREFIX##_coo_vec_alloc(size_t size, size_t nnz) { \\\n");
    printf("        PREFIX##_coo_vec v; \\\n");
    printf("        v.size = size; \\\n");
    printf("        v.nnz = nnz; \\\n");
    printf("        v.values = (TYPE*)calloc(nnz, sizeof(TYPE)); \\\n");
    printf("        v.indices = (size_t*)calloc(nnz, sizeof(size_t)); \\\n");
    printf("        return v; \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_coo_vec_free(PREFIX##_coo_vec *v) { \\\n");
    printf("        if (v->values) free(v->values); \\\n");
    printf("        if (v->indices) free(v->indices); \\\n");
    printf("        v->values = NULL; \\\n");
    printf("        v->indices = NULL; \\\n");
    printf("        v->size = 0; \\\n");
    printf("        v->nnz = 0; \\\n");
    printf("    } \\\n");
    printf("    PREFIX##_dense_mat PREFIX##_dense_mat_alloc(size_t rows, size_t cols) { \\\n");
    printf("        PREFIX##_dense_mat m; \\\n");
    printf("        m.rows = rows; \\\n");
    printf("        m.cols = cols; \\\n");
    printf("        m.data = (TYPE*)calloc(rows * cols, sizeof(TYPE)); \\\n");
    printf("        return m; \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_mat_free(PREFIX##_dense_mat *m) { \\\n");
    printf("        if (m->data) free(m->data); \\\n");
    printf("        m->data = NULL; \\\n");
    printf("        m->rows = 0; \\\n");
    printf("        m->cols = 0; \\\n");
    printf("    } \\\n");
    printf("    PREFIX##_csr_mat PREFIX##_csr_mat_alloc(size_t rows, size_t cols, size_t nnz) { \\\n");
    printf("        PREFIX##_csr_mat m; \\\n");
    printf("        m.rows = rows; \\\n");
    printf("        m.cols = cols; \\\n");
    printf("        m.nnz = nnz; \\\n");
    printf("        m.values = (TYPE*)calloc(nnz, sizeof(TYPE)); \\\n");
    printf("        m.col_indices = (size_t*)calloc(nnz, sizeof(size_t)); \\\n");
    printf("        m.row_ptr = (size_t*)calloc(rows + 1, sizeof(size_t)); \\\n");
    printf("        return m; \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_csr_mat_free(PREFIX##_csr_mat *m) { \\\n");
    printf("        if (m->values) free(m->values); \\\n");
    printf("        if (m->col_indices) free(m->col_indices); \\\n");
    printf("        if (m->row_ptr) free(m->row_ptr); \\\n");
    printf("        m->values = NULL; \\\n");
    printf("        m->col_indices = NULL; \\\n");
    printf("        m->row_ptr = NULL; \\\n");
    printf("        m->rows = 0; \\\n");
    printf("        m->cols = 0; \\\n");
    printf("        m->nnz = 0; \\\n");
    printf("    } \\\n");
    printf("    PREFIX##_dia_mat PREFIX##_dia_mat_alloc(size_t rows, size_t cols, size_t num_diags) { \\\n");
    printf("        PREFIX##_dia_mat m; \\\n");
    printf("        m.rows = rows; \\\n");
    printf("        m.cols = cols; \\\n");
    printf("        m.num_diags = num_diags; \\\n");
    printf("        size_t max_diag_len = (rows < cols) ? rows : cols; \\\n"); // Simplified diag len
    printf("        m.data = (TYPE*)calloc(num_diags * max_diag_len, sizeof(TYPE)); \\\n");
    printf("        m.offsets = (int*)calloc(num_diags, sizeof(int)); \\\n");
    printf("        return m; \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dia_mat_free(PREFIX##_dia_mat *m) { \\\n");
    printf("        if (m->data) free(m->data); \\\n");
    printf("        if (m->offsets) free(m->offsets); \\\n");
    printf("        m->data = NULL; \\\n");
    printf("        m->offsets = NULL; \\\n");
    printf("        m->rows = 0; \\\n");
    printf("        m->cols = 0; \\\n");
    printf("        m->num_diags = 0; \\\n");
    printf("    } \\\n");

    printf("    void PREFIX##_dense_vec_map_to_device(PREFIX##_dense_vec *v) { \\\n");
    printf("        #pragma omp target enter data map(to: v[0], v->data[0:v->size]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_vec_update_from_device(PREFIX##_dense_vec *v) { \\\n");
    printf("        #pragma omp target update from(v->data[0:v->size]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_vec_unmap_from_device(PREFIX##_dense_vec *v) { \\\n");
    printf("        #pragma omp target exit data map(from: v->data[0:v->size], v[0]) \\\n");
    printf("    } \\\n");

    printf("    void PREFIX##_coo_vec_map_to_device(PREFIX##_coo_vec *v) { \\\n");
    printf("        #pragma omp target enter data map(to: v[0], v->values[0:v->nnz], v->indices[0:v->nnz]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_coo_vec_update_from_device(PREFIX##_coo_vec *v) { \\\n");
    printf("        #pragma omp target update from(v->values[0:v->nnz]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_coo_vec_unmap_from_device(PREFIX##_coo_vec *v) { \\\n");
    printf("        #pragma omp target exit data map(from: v->values[0:v->nnz], v->indices[0:v->nnz], v[0]) \\\n");
    printf("    } \\\n");

    printf("    void PREFIX##_dense_mat_map_to_device(PREFIX##_dense_mat *m) { \\\n");
    printf("        #pragma omp target enter data map(to: m[0], m->data[0:m->rows*m->cols]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_mat_update_from_device(PREFIX##_dense_mat *m) { \\\n");
    printf("        #pragma omp target update from(m->data[0:m->rows*m->cols]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dense_mat_unmap_from_device(PREFIX##_dense_mat *m) { \\\n");
    printf("        #pragma omp target exit data map(from: m->data[0:m->rows*m->cols], m[0]) \\\n");
    printf("    } \\\n");

    printf("    void PREFIX##_csr_mat_map_to_device(PREFIX##_csr_mat *m) { \\\n");
    printf("        #pragma omp target enter data map(to: m[0], m->values[0:m->nnz], m->col_indices[0:m->nnz], m->row_ptr[0:m->rows+1]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_csr_mat_update_from_device(PREFIX##_csr_mat *m) { \\\n");
    printf("        #pragma omp target update from(m->values[0:m->nnz]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_csr_mat_unmap_from_device(PREFIX##_csr_mat *m) { \\\n");
    printf("        #pragma omp target exit data map(from: m->values[0:m->nnz], m->col_indices[0:m->nnz], m->row_ptr[0:m->rows+1], m[0]) \\\n");
    printf("    } \\\n");

    printf("    void PREFIX##_dia_mat_map_to_device(PREFIX##_dia_mat *m) { \\\n");
    printf("        size_t max_diag_len = (m->rows < m->cols) ? m->rows : m->cols; \\\n");
    printf("        #pragma omp target enter data map(to: m[0], m->data[0:m->num_diags * max_diag_len], m->offsets[0:m->num_diags]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dia_mat_update_from_device(PREFIX##_dia_mat *m) { \\\n");
    printf("        size_t max_diag_len = (m->rows < m->cols) ? m->rows : m->cols; \\\n");
    printf("        #pragma omp target update from(m->data[0:m->num_diags * max_diag_len]) \\\n");
    printf("    } \\\n");
    printf("    void PREFIX##_dia_mat_unmap_from_device(PREFIX##_dia_mat *m) { \\\n");
    printf("        size_t max_diag_len = (m->rows < m->cols) ? m->rows : m->cols; \\\n");
    printf("        #pragma omp target exit data map(from: m->data[0:m->num_diags * max_diag_len], m->offsets[0:m->num_diags], m[0]) \\\n");
    printf("    } \n\n");

}

int main() {
    print_mem_macros();
    return 0;
}
